[params]
title = "Navy Linux"
titleSeparator = "-"
copyright = "© 2021 Navy Linux Project. All rights reserved."
baseURL = "https://navylinux.com"
languageCode = "en-us"

[params.socialmedia]
slack = "https://join.slack.com/t/navylinux/shared_invite/zt-kj37s3lu-~JkloN8UHgH38cyuD97V7Q"
twitter = "https://twitter.com/NavyLinux"
github = "https://github.com/navy-linux/"
facebook = "https://www.facebook.com/navylinux"
linkedin = "https://www.linkedin.com/company/navy-linux/"
blog = "https://blog.navylinux.com/"
wiki = "https://wiki.navylinux.com/"
bugs = "https://bugs.navylinux.com/"
git = "https://git.navylinux.com/"
forums = "https://forums.navylinux.com/"