disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
title = "Navy Linux"
titleSeparator = "-"
copyright = "© 2021 Navy Foundation (Delaware Non-Profit Corporation 501c3) All rights reserved."
baseURL = ""
relativeURLs = true
languageCode = "en-us"
themeColor = "#1d405d"


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[module]
      source = "assets/scss/app.scss"



[menu]
[[menu.main]]
    name = "About"
    baseURL = "/about/"
    weight = 1


[params.socialmedia]
slack = "//navylinux.slack.com/"
download = "/download/"
donate = "//donate.navylinux.org/"
twitter = "//twitter.com/NavyLinux"
github = "//github.com/navy-linux/"
facebook = "//www.facebook.com/navylinux"
linkedin = "//www.linkedin.com/company/navy-linux/"
blog = "//blog.navylinux.org/"
bugs = "//bugs.navylinux.org/"
git = "//git.navylinux.org/"
forums = "//forums.navylinux.org/"
mirror = "//mirror.navylinux.org/"
mirrorlist = "/mirrorlist/"
jenkins = "//build.navylinux.org/"
about = "/about/"
faqs = "/wiki/faqs/"
contribute="/wiki/contribute/"
Infrastructure="/infrastructure/"
wiki="/wiki/"
errata="/errata/"
sponsors = "/sponsors/"
news = "/news/"
developerguide = "/wiki/developer-guide/"
navylinuxbeta = "/navylinuxbeta/"
fontawesome = "/fontawesome/css/"
lineawesome = "/line-awesome/css/"
jquery = "/js/"
migrate = "/wiki/migrate/"

gitbase = "//git.navylinux.org/website/navylinux-org/-/tree/main/content/"

bugurl = "https://git.navylinux.org/website/navylinux-org/-/issues"


[permalinks]
	posts = "/:title/"



[markup.goldmark.renderer]
unsafe= true
