disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
title = "Navy Linux"
titleSeparator = "-"
copyright = "© 2021 Navy Linux Project. All rights reserved."
baseURL = "https://navylinux.org"
languageCode = "en-us"
themeColor = "#15387e"

[menu]
[[menu.main]]
    name = "About"
    baseURL = "/about/"
    weight = 1

[params.socialmedia]
slack = "https://join.slack.com/t/navylinux/shared_invite/zt-masyd8ir-uQAu3XsAJ7ai7LiLjmXvfg"
twitter = "https://twitter.com/NavyLinux"
github = "https://github.com/navy-linux/"
facebook = "https://www.facebook.com/navylinux"
linkedin = "https://www.linkedin.com/company/navy-linux/"
blog = "https://blog.navylinux.org/"
wiki = "https://wiki.navylinux.org/"
bugs = "https://bugs.navylinux.org/"
git = "https://git.navylinux.org/"
forums = "https://forums.navylinux.org/"
mirror = "https://mirror.navylinux.org/"
mirrorlist = "https://mirrorlist.navylinux.org/"
jenkins = "https://build.navylinux.org/"
about = "/about/"