disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
title = "Navy Linux"
titleSeparator = "-"
copyright = "© 2021 Navy Linux Project. All rights reserved."
baseURL = "https://navylinux.org"
languageCode = "en-us"
themeColor = "#15387e"

[menu]
[[menu.main]]
    name = "About"
    baseURL = "/about/"
    weight = 1


[params.socialmedia]
slack = "//navylinux.slack.com/"
twitter = "//twitter.com/NavyLinux"
github = "//github.com/navy-linux/"
facebook = "//www.facebook.com/navylinux"
linkedin = "//www.linkedin.com/company/navy-linux/"
blog = "//blog.navylinux.org/"
wiki = "//wiki.navylinux.org/"
bugs = "//bugs.navylinux.org/"
git = "//git.navylinux.org/"
forums = "//forums.navylinux.org/"
mirror = "//mirror.navylinux.org/"
mirrorlist = "/mirrorlist/"
jenkins = "//build.navylinux.org/"
about = "/about/"
faqs = "/about/faqs/"


bugurl = "https://git.navylinux.org/website/navylinux-org/-/issues"


[permalinks]
	posts = "/:title/"


